# Generated by Django 5.0.6 on 2024-07-03 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DormInfo",
            fields=[
                (
                    "dorm_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "dorm_class",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=1
                    ),
                ),
                (
                    "dorm_type",
                    models.CharField(
                        choices=[("solo", "Solo"), ("shared", "Shared")], max_length=6
                    ),
                ),
                ("num_occupied", models.PositiveIntegerField(default=0)),
                (
                    "occupied_status",
                    models.CharField(
                        choices=[("yes", "Yes"), ("no", "No")], max_length=3
                    ),
                ),
                (
                    "dorm_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TenantProfile",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("last_name", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("age", models.PositiveIntegerField()),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("school", models.CharField(max_length=255)),
                ("degree_program", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Bookings",
            fields=[
                (
                    "booking_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "book_status",
                    models.CharField(
                        choices=[
                            ("For Waitlisted", "For Waitlisted"),
                            ("For Payment", "For Payment"),
                            ("For Occupying", "For Occupying"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "dorm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dormmatch.dorminfo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dormmatch.tenantprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TransactionLog",
            fields=[
                (
                    "transaction_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("ref_number", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("Paid", "Paid"), ("Pending", "Pending")],
                        max_length=10,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dormmatch.bookings",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bookings",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dormmatch.transactionlog",
            ),
        ),
    ]
