# Generated by Django 5.0.6 on 2024-07-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dormmatch", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantprofile",
            name="contact_number",
            field=models.CharField(max_length=15),
        ),
    ]
