# Generated by Django 5.0.6 on 2024-07-03 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dormmatch", "0002_alter_tenantprofile_contact_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dorminfo",
            old_name="num_occupied",
            new_name="capacity",
        ),
    ]
