# Generated by Django 5.0.6 on 2024-07-05 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dormmatch", "0004_alter_dorminfo_dorm_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookings",
            name="transaction",
        ),
    ]
